### ISSUE TITLE
Workshop #3 Add more info for Metrics and Monitoring

### ISSUE THREAD

**Issue by moficodes** [IBM/openshift101#28]
Right now the metrics and monitoring shows what exists in openshift. But it does not show any valuable info as to why user benefits from these features. 

Maybe we need to think about some way to bring meaning to this. 

We could do something like:
- We could switch order of this workshop to autoscale. So we can show the graph when usage went too high.
- Run higher workload that adds some pressure of resource.
- Change/Add a path to our application that has some random failure maybe.

**Comment by jjasghar** [comment]
I'm not sure this is still relevant. If it is, please reopen and we'll work to a resolution.
