### ISSUE TITLE
about exercise-6  operational procedure

### ISSUE THREAD

**Issue by daihiraoka** [IBM/openshift101#31]
Hello,

I think the exercise-6 procedure doesn't use the OpenShift function enough.

In exercise-6 uses S2I docker strategy.

In exercise-1, S2I uses SourceStrategy.

The big difference between excise1 and excise6 is that there is a buildconfig in exercise-1 but not in exercise-6.

In exercise-6, if we change the source code of the application, we have to do a docker build and push the docker image to Docker Hub again.

In exercise-1, we change the application source code on GitHub, and when we click the start-build button on the GUI, build and deployment will start automatically with OpenShift.

If we make a procedure like excrcise-1 with cli, I think the following procedure is good.

```
$ oc new-project example-health-ns

$ oc project example-health-ns

- [if you need ] Red Hat UBI Image import to openshift project
$ oc import-image ubi7/nodejs-10 --from=registry.access.redhat.com/ubi7/nodejs-10 -n openshift --confirm

$ oc get is -n openshift
NAME             DOCKER REPO                                                 TAGS                          UPDATED
nodejs           docker-registry.default.svc:5000/openshift/nodejs           0.10,10,4 + 4 more...         5 weeks ago
nodejs-10        docker-registry.default.svc:5000/openshift/nodejs-10        latest                        2 hours ago

openshift/nodejs:10   <-- original centos template  
nodejs-10:latest <- Red Hat UBI Image(RHEL7)


$ oc new-app openshift/nodejs-10~https://github.com/daihiraoka/node-s2i-openshift.git --name='patientui' --context-dir='/site'

--> Found image fca7ff7 (3 weeks old) in image stream "openshift/nodejs-10" under tag "latest" for "openshift/nodejs-10"

    * A source build using source code from https://github.com/daihiraoka/node-s2i-openshift.git will be created
      * The resulting image will be pushed to image stream tag "patientui:latest"
      * Use 'start-build' to trigger a new build
    * This image will be deployed in deployment config "patientui"
    * Port 8080/tcp will be load balanced by service "patientui"
      * Other containers can access this service through the hostname "patientui"

--> Creating resources ...
    imagestream.image.openshift.io "patientui" created
    buildconfig.build.openshift.io "patientui" created
    deploymentconfig.apps.openshift.io "patientui" created
    service "patientui" created
--> Success
    Build scheduled, use 'oc logs -f bc/patientui' to track its progress.
    Application is not exposed. You can expose services to the outside world by executing one or more of the commands below:
     'oc expose svc/patientui' 
    Run 'oc status' to view your app.
    
$ oc get pod
NAME                                  READY     STATUS      RESTARTS   AGE
patientui-1-build                     0/1       Completed   0          2m
patientui-1-xjmbk                     1/1       Running     0          5m

$ oc expose svc/patientui
route.route.openshift.io/patientui exposed

$ oc get route
NAME       HOST/PORT                                      PATH  SERVICES  PORT TERMINATION WILDCARD
patientui  patientui-example-health-ns.***.containers.appdomain.cloud      patientui 8080-tcp         None


============================================================
Change the application source code on GitHub.
===========================================================

- check buildconfig
$ oc get bc
NAME        TYPE      FROM      LATEST
patientui   Source    Git       1

- start build
$ oc start-build patientui
build.build.openshift.io/patientui-2 started

$ oc get bc
NAME        TYPE      FROM      LATEST
patientui   Source    Git       2

- The build1 pod has terminated, and the build2 pod has started.
$ oc get pod
patientui-1-build                     0/1       Completed     0          3m
patientui-1-xjmbk                     0/1       Terminating   0          6m
patientui-2-bsgpr                     1/1       Running       0          11s
patientui-2-build                     0/1       Completed     0          45s
```

Best,
Daisuke Hiraoka

**Comment by daihiraoka** [comment]
- BuildConfig

```
$ oc get bc -o yaml
apiVersion: v1
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: patientui
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: patientui:latest
    source:
      contextDir: /site
      git:
        uri: https://github.com/daihiraoka/node-s2i-openshift.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs-10:latest
          namespace: openshift
      type: Source
```

**Comment by remkohdev** [comment]
Hi @daihiraoka yes, you are right. I think another way to look at exercise-1 vs exercise-6 is that it is UI based versus cli based approach. I will add a cli based S2I example and a Jenkins on Openshift example soon, currently located here https://code.remkohde.com/openshift/builds/source-to-image-s2i/build-and-run-from-source

I will take your comment, include it in the pure S2I with source strategy from cli and explain the different strategies more clearly. Thanks for your feedback. Let me know if you have any further feedback or contribution, it is always very welcome.

**Comment by daihiraoka** [comment]
Hi @remkohdev 
Thank you for your reply!

I think exercise-6 should not use docker.

The people who learn in this workshop are developers, operators, and sales. I think the easiest way is as good as possible.

When using OpenShift, it's important to learn that we can build and deploy applications without using docker, whether using GUI or CLI.　Most people will not have the opportunity to use docker when using OpenShift in commercial use.　This is one of the features of OpenShift.

I think the # 31 procedure is the best, 
but I can agree if we change the current excise6 procedure as follows use case:

Actor: 
 1. Solution Architect
 2. Developer

Steps:

 1. Solution Architect

```
- Build and Push the base image to your public Docker Hub Registry.
  $ docker build --no-cache -t example-health .
  $ docker tag example-health:latest <username>/example-health:1.0.0
  $ docker login -u <username>
  $ docker push <username>/example-health:1.0.0

- Import the base image as a template into the OpenShift project
oc import-image <username>/example-health --from=<username>/example-health:1.0.0 -n openshift --confirm
```
 
2. Developer

```
- Deploy the Example Health app using  template(base image) and  source code (github)
$ oc new-app openshift/example-health:1.0.0~https://github.com/daihiraoka/node-s2i-openshift.git --name='patientui' --context-dir='/site'
```

I think that The principle of openshift build is to separate base image(docker image) and Application's source code.

- Solution Architect creates a base image (Docker Image) to maintain the OS and middleware.

- Developer uses the base image created by Solution Architect as a template.(developer does not use docker.)

In OpenShift, I think it's good to emphasize that Solution Architect and Developer can be separated by interest. [separation of concerns]


**I looked at your blog.**
https://code.remkohde.com/openshift/builds/source-to-image-s2i/build-and-run-from-source

**I think this is a great job!** 

jenkins pipline uses the github repository for the source code.

I'm sorry, only one was interested.

In build-and-run-from-source, 

```
$ oc new-app --name springclient registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift~. 
```
I thought that it would be better to specify the github repository when specifying the source code for oc new-app.

I think the articles on the jenkins pipeline are very easy to understand and great.

Thank you!
Daisuke Hiraoka

**Comment by remkohdev** [comment]
Agree, the source strategy should be exercise 6, exercise-7 use docker and exercise-8 use Jenkinsfile. There are many developers and organizations that use multi-cloud and have an existing baseline or CI/CD Pipeline using docker or Jenkins, so I like to cover those 3 main strategies. I will take your points and input and rewrite/add exercise 6,7,8.

**Comment by jjasghar** [comment]
I don't think this is still relevant to what we are trying to accomplish. If it is, please reopen and we'll work to make it better. Thanks!
